### ISSUE TITLE
Meteor packade is not working

### ISSUE THREAD

**Issue by alesch** [buildhybrid/assets#3]
When using this package with Meteor 1.1.0.1 I get the following stack trace.
But using assets from the command line, using the same config.assets works fine.

```
TypeError: undefined is not a function
    at /Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/index.js:56:11
    at /Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/index.js:175:7
    at done (/Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/node_modules/async/lib/async.js:135:19)
    at /Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/node_modules/async/lib/async.js:32:16
    at /Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/index.js:158:11
    at /Users/alex/.meteor/packages/hybrid_assets/.0.2.4.e8mm1d++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/node_modules/gm/lib/compare.js:91:7
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by andrewreedy** [comment]
I'll check this out tomorrow and get back to you.

**Comment by CEOGavin** [comment]
+1

**Comment by jaskinn** [comment]
+1

It doesn't like 'callback()'

**Comment by CEOGavin** [comment]
@andrewreedy any update?

**Comment by andrewreedy** [comment]
@CEOGavin Hey I've been out of the OS world for a bit! I'm going to catch up on issues this weekend. Sorry for the delay.

**Comment by chrisco23** [comment]
The Meteor package is designed to create the assets when "meteor run" is run?

@alesch I just added this package and hit the same issue you apparently had 2.5 months ago.  I take it you decided to run it from the command line?  So did you just do all the processing outside of your Meteor app and copy the files into the app??  I'm working on my first hybrid app and I just want (afaik) the favicon, the android app icon, and the splash page, to replace the generic Meteor images.

**Comment by alesch** [comment]
@chrisco23 yes, you are right. I gave up on this package and got it fixed outside. I do not remember now how I did it, :-(

**Comment by chrisco23** [comment]
Ok.  I'm trying to make my first hybrid app, and I've found the specs for what images I need (I believe) here: https://stackoverflow.com/questions/26957503/meteor-way-to-specify-icon-and-launch-screen-of-an-app
But not being a designer, I don't really want to try to create all these images.  It may be placeholder art to start out with anyway, but I want it to function properly in the various sizes/devices (just Android to start).

**Comment by gwendall** [comment]
+1

**Comment by dfischer** [comment]
Getting the same error...

**Comment by erkkimon** [comment]
+1

**Comment by richardgsands** [comment]
+1

**Comment by ManuelThurner** [comment]
+1
