### ISSUE TITLE
ReferenceError: obj is not defined

### ISSUE THREAD

**Issue by vertangelx** [buildhybrid/assets#6]
Just added the `hybrid:assets` package and `private/logo.png` and this error appears when meteor starts:

    => Started proxy.                             
    => Started MongoDB.                           
                                                  
    <runJavaScript-57>:32
        compileStep.error({message: obj});                               // 19
                                    ^
    ReferenceError: obj is not defined
        at [object Object].assets.error (packages/buildAssets/plugin/build-assets.js:19:1)
        at gm.<anonymous> (/Users/vertangelx/.meteor/packages/hybrid_assets/.0.2.4.1748cw7++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/index.js:315:28)
        at cb (/Users/vertangelx/.meteor/packages/hybrid_assets/.0.2.4.1748cw7++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/node_modules/gm/lib/command.js:301:16)
        at ChildProcess._spawn.proc.on.onExit (/Users/vertangelx/.meteor/packages/hybrid_assets/.0.2.4.1748cw7++os+web.browser+web.cordova/plugin.buildAssets.os/npm/buildAssets/node_modules/hybrid-assets/node_modules/gm/lib/command.js:283:9)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12)

and here's `assets.config`

    {
        "appIcons": {
            "source": "private/icon.png",
            "output": "resources/icons/",
            "type": ["ios", "android", "chromeext", "mac"]
        },
        "webIcons": {
            "source": "private/icon.png",
            "output": "public/assets/images/favicon/",
            "type": ["favicon"]
        }
    }

**Comment by gumyn** [comment]
I've exactly the same problem ...

+1

**Comment by jimmiebtlr** [comment]
I believe I got this error when I forgot to install graphicsmagick.

**Comment by chip** [comment]
I'm running into this and I have graphicsmagick installed (version 1.3.23_1).
